### ISSUE TITLE
Additional message after an After() property that returns true, for the Wear action. 

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#67] opened 2021-01-18 08:12 UTC
There seems to be a problem with the property After and the action Wear. There is an extra message as if After returned false.
```
> wear hat                                                                            
(first taking the hat)                                                                
You put the hat on your head.                                                         
You are already wearing it. 
```
```
!% -~S
!% $OMIT_UNUSED_ROUTINES=1

Constant STATUSLINE_SCORE; Statusline score;
Constant INITIAL_LOCATION_VALUE = Library;

Include "globals.h"; Include "puny.h";

Object Library "The Library"
	with description "You are in a library."
   has light;

Object -> hat "hat"
   with name 'hat',
   After [;
      Take, Wear:
         give self worn;
         "You put the hat on your head."; 
   ],
   has clothing ~worn;

[ Initialise; ];
```

**Comment by auraes** [comment] 2021-01-18 08:28
I have modified my example which is more in line with what I wanted to do.  
It's the Take, Wear on the same entry that is problematic, and I don't know if it's allowed with PunyInform.

**Comment by fredrikr** [comment] 2021-01-18 08:48
It's perfectly allowed to use the same entry for two actions.

The problem is that you perform two different actions here. The library sees that you need to be holding the item before you can wear it, so it issues an implicit Take action, but it's still a full-blown action including before and after rules. Then it completes the Wear action, including running after rules. So the after rule is run twice.

One way to fix it is to not do anything in After if it's an implicit Take. When the implicit Take is running, keep_silent is set to true.

```
   after [;
      Take, Wear:
          if(keep_silent==false) {
             give self worn;
            "You put the hat on your head.";
          }
   ],
```

**Comment by fredrikr** [comment] 2021-01-18 09:07
Ah, with your modified code my answer isn't quite correct. Since the Wear action now fails, the after rule of the Wear action is not run.

My proposed solution works though.

And I don't think we should change anything in the library regarding this.

**Comment by auraes** [comment] 2021-01-18 10:34
The suggested solution with keep_silent seems successful:
```
   After [;
      Take:
         if(keep_silent==false) {
            give self worn;
            "You put the hat on your head. (After Take)";
         }
      Wear:
         "You put the hat on your head. (After Wear)"; 
   ],
```
```
> get hat                                                                             
You put the hat on your head. (After Take)                                                  
                                                                                      
> drop hat                                                                            
(first taking off the hat)                                                            
Dropped.                                                                              
                                                                                      
> wear hat                                                                            
(first taking the hat)                                                                
You put the hat on your head. (After Wear)                                                  
                                                                                      
> remove hat                                                                          
You take off the hat.                                                                 
                                                                                      
> wear hat                                                                            
You put the hat on your head. (After Wear) 
```

**Comment by fredrikr** [comment] 2021-01-18 10:40
Closing.

**Closed by fredrikr** 2021-01-18 10:40 UTC
